# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e873bfe3ace066cb672480962820d9e7809172035c84a37ebba000393bec7b86f2f63f93776de03e399cb39523bdd31ff177f97fa44f33158acd17dea04c86df

test:
  secret_key_base: 3a2f2b095accda82b0a2660f535c168610c534b5c4d24f093d94c03d37c684123794e048f2b4dd748b47338c05250c0e11e83d57971027076408901c5f9a6cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
